# Sobrescreve para ambiente de desenvolvimento
spring.datasource.url=jdbc:postgresql://localhost:5432/brics_dev
spring.datasource.username=devuser
spring.datasource.password=devpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true